kind: Deployment
apiVersion: apps/v1
metadata:
  name: webapp-deployment22
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: "tasyuminahito/webapp-cicd:tasyuminahito/webapp-cicd:0.0.2\ntasyuminahito/webapp-cicd:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: django
