kind: Deployment
apiVersion: apps/v1
metadata:
  name: webapp-deployment10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: "tasyuminahito/webapp-cicd:main"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: django
front:
  imageTag: ""
---
kind: Service
apiVersion: v1
metadata:
  name: webapp-deployment10
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8000
      name: django
  type: NodePort
front:
  imageTag: ""
