kind: Deployment
apiVersion: apps/v1
metadata:
  name: webapp-deployment18
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: "tasyuminahito/webapp-cicd:main"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: django
        - tasyuminahito/webapp-cicd:v16
front:
  imageTag: ""
---
kind: Service
apiVersion: v1
metadata:
  name: webapp-deployment18
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8000
      name: django
  type: NodePort
  template:
    spec:
      containers:
        - null
        - tasyuminahito/webapp-cicd:v16
front:
  imageTag: ""
